name = "pickles-website"
compatibility_date = "2024-05-13"
main = "./_worker.js"  # (Required placeholder to deploy static assets)

[assets]
directory = "."

[[kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "be07bdccc1324fb0bb70583735f62de1"
