name = "pickles-website"
compatibility_date = "2024-05-13"

[site]
bucket = "."
entry-point = "."

[build]
command = ""
publish = "."

[[routes]]
pattern = "/"
script_name = "pickles-website"

[[routes]]
pattern = "/*"
script_name = "pickles-website"
