name = "pickles-website"
type = "javascript"
compatibility_date = "2024-05-13"

[site]
bucket = "."         # ✅ this is okay *if* index.html is in root
entry-point = "."    # ✅ add this to avoid errors

[[kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "be07bdccc1324fb0bb70583735f62de1"
